"""
Comprehensive registry of all SGLang serve CLI arguments.
Each entry includes: name, category, type, default, description, choices, example, dependent_args.
"""

ARG_CATEGORIES = [
    "Model & Tokenizer",
    "Server & Networking",
    "Parallelism & Distribution",
    "Memory & KV Cache",
    "Scheduling",
    "Quantization & Data Types",
    "Multimodal",
    "Speculative Decoding",
    "MoE & Expert Parallel",
    "Monitoring & Logging",
    "LoRA Adapters",
    "Advanced",
]

ARGS_REGISTRY = [
    # ===== Model & Tokenizer =====
    {
        "name": "--model-path",
        "short": "--model",
        "category": "Model & Tokenizer",
        "type": "string",
        "default": "(required)",
        "description": "HuggingFace repo ID (e.g., meta-llama/Llama-3.1-8B-Instruct) or local path to model weights",
        "example": "--model-path meta-llama/Llama-3.1-8B-Instruct",
        "required": True,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--tokenizer-path",
        "short": None,
        "category": "Model & Tokenizer",
        "type": "string",
        "default": "Same as --model-path",
        "description": "Path to a separate tokenizer (if different from model path)",
        "example": "--tokenizer-path /path/to/tokenizer",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--tokenizer-mode",
        "short": None,
        "category": "Model & Tokenizer",
        "type": "choice",
        "default": "auto",
        "choices": ["auto", "slow"],
        "description": "Tokenizer mode: 'auto' uses fast tokenizer if available, 'slow' forces slow tokenizer",
        "example": "--tokenizer-mode slow",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--tokenizer-backend",
        "short": None,
        "category": "Model & Tokenizer",
        "type": "choice",
        "default": "huggingface",
        "choices": ["huggingface", "fastokens"],
        "description": "Tokenizer backend library to use",
        "example": "--tokenizer-backend fastokens",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--trust-remote-code",
        "short": None,
        "category": "Model & Tokenizer",
        "type": "flag",
        "default": "False",
        "description": "Allow loading models with custom HuggingFace modeling code. Required for some community models.",
        "example": "--trust-remote-code",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--context-length",
        "short": None,
        "category": "Model & Tokenizer",
        "type": "int",
        "default": "From model config",
        "description": "Override the model's maximum context length (number of tokens). Useful for extending context.",
        "example": "--context-length 32768",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--revision",
        "short": None,
        "category": "Model & Tokenizer",
        "type": "string",
        "default": "main",
        "description": "Git branch, tag, or commit hash for the model on HuggingFace Hub",
        "example": "--revision v1.0",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--load-format",
        "short": None,
        "category": "Model & Tokenizer",
        "type": "choice",
        "default": "auto",
        "choices": ["auto", "pt", "safetensors", "npcache", "dummy", "sharded_state", "gguf", "bitsandbytes", "mistral", "layered"],
        "description": "Format for loading model weights. 'auto' tries safetensors first, falls back to pt.",
        "example": "--load-format safetensors",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--dtype",
        "short": None,
        "category": "Model & Tokenizer",
        "type": "choice",
        "default": "auto",
        "choices": ["auto", "half", "float16", "bfloat16", "float", "float32"],
        "description": "Data type for model weights and computation. 'auto' selects based on model config.",
        "example": "--dtype bfloat16",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--model-impl",
        "short": None,
        "category": "Model & Tokenizer",
        "type": "choice",
        "default": "auto",
        "choices": ["auto", "sglang", "transformers"],
        "description": "Model implementation backend. 'auto' tries sglang native first, falls back to transformers.",
        "example": "--model-impl transformers",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--is-embedding",
        "short": None,
        "category": "Model & Tokenizer",
        "type": "flag",
        "default": "False",
        "description": "Run the model as an embedding model (returns vectors instead of text)",
        "example": "--is-embedding",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--skip-tokenizer-init",
        "short": None,
        "category": "Model & Tokenizer",
        "type": "flag",
        "default": "False",
        "description": "Skip tokenizer initialization on startup",
        "example": "--skip-tokenizer-init",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },

    # ===== Server & Networking =====
    {
        "name": "--host",
        "short": None,
        "category": "Server & Networking",
        "type": "string",
        "default": "127.0.0.1",
        "description": "Bind address for the HTTP server. Use 0.0.0.0 to allow external connections.",
        "example": "--host 0.0.0.0",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--port",
        "short": None,
        "category": "Server & Networking",
        "type": "int",
        "default": "30000",
        "description": "HTTP server port",
        "example": "--port 30000",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--api-key",
        "short": None,
        "category": "Server & Networking",
        "type": "string",
        "default": "None",
        "description": "API key required for all requests (similar to OpenAI API key)",
        "example": "--api-key sk-sglang-secret",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--served-model-name",
        "short": None,
        "category": "Server & Networking",
        "type": "string",
        "default": "Model path name",
        "description": "Custom name for the model exposed in the API (GET /v1/models)",
        "example": "--served-model-name my-model",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--ssl-keyfile",
        "short": None,
        "category": "Server & Networking",
        "type": "string",
        "default": "None",
        "description": "Path to SSL key file for HTTPS",
        "example": "--ssl-keyfile /path/to/key.pem",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--ssl-certfile",
        "short": None,
        "category": "Server & Networking",
        "type": "string",
        "default": "None",
        "description": "Path to SSL certificate file for HTTPS",
        "example": "--ssl-certfile /path/to/cert.pem",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--enable-http2",
        "short": None,
        "category": "Server & Networking",
        "type": "flag",
        "default": "False",
        "description": "Enable HTTP/2 support",
        "example": "--enable-http2",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--grpc-mode",
        "short": None,
        "category": "Server & Networking",
        "type": "flag",
        "default": "False",
        "description": "Run in gRPC mode instead of HTTP",
        "example": "--grpc-mode",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--chat-template",
        "short": None,
        "category": "Server & Networking",
        "type": "string",
        "default": "From tokenizer",
        "description": "Custom chat template name or path for formatting multi-turn conversations",
        "example": "--chat-template tool_use",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },

    # ===== Parallelism & Distribution =====
    {
        "name": "--tensor-parallel-size",
        "short": "--tp",
        "category": "Parallelism & Distribution",
        "type": "int",
        "default": "1",
        "description": "Number of GPUs for tensor parallelism. Splits model layers across GPUs to reduce memory per GPU.",
        "choices": ["1", "2", "4", "8"],
        "example": "--tensor-parallel-size 2",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--pipeline-parallel-size",
        "short": "--pp",
        "category": "Parallelism & Distribution",
        "type": "int",
        "default": "1",
        "description": "Number of stages for pipeline parallelism. Splits layers into stages across GPUs.",
        "example": "--pipeline-parallel-size 2",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--data-parallel-size",
        "short": "--dp",
        "category": "Parallelism & Distribution",
        "type": "int",
        "default": "1",
        "description": "Number of data parallel replicas. Replicates full model across GPUs for highest throughput.",
        "example": "--data-parallel-size 2",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--expert-parallel-size",
        "short": "--ep",
        "category": "Parallelism & Distribution",
        "type": "int",
        "default": "1",
        "description": "Number of GPUs for expert parallelism (MoE models). Distributes experts across GPUs.",
        "example": "--expert-parallel-size 2",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--nnodes",
        "short": None,
        "category": "Parallelism & Distribution",
        "type": "int",
        "default": "1",
        "description": "Number of nodes for multi-node tensor parallelism",
        "example": "--nnodes 2",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--node-rank",
        "short": None,
        "category": "Parallelism & Distribution",
        "type": "int",
        "default": "0",
        "description": "Rank of this node in multi-node setup (0-indexed)",
        "example": "--node-rank 0",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--dist-init-addr",
        "short": None,
        "category": "Parallelism & Distribution",
        "type": "string",
        "default": "None",
        "description": "Master address for distributed initialization (required for multi-node)",
        "example": "--dist-init-addr 192.168.1.1:5000",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--enable-dp-attention",
        "short": None,
        "category": "Parallelism & Distribution",
        "type": "flag",
        "default": "False",
        "description": "Enable data parallel attention (hybrid: DP for attention, TP for FFN)",
        "example": "--enable-dp-attention",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },

    # ===== Memory & KV Cache =====
    {
        "name": "--mem-fraction-static",
        "short": None,
        "category": "Memory & KV Cache",
        "type": "float",
        "default": "0.9",
        "description": "Fraction of GPU memory allocated for weights + KV cache pool. Lower values reserve more for overhead.",
        "example": "--mem-fraction-static 0.8",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--max-total-tokens",
        "short": None,
        "category": "Memory & KV Cache",
        "type": "int",
        "default": "Auto-calculated",
        "description": "Maximum number of tokens in the KV cache pool. Auto-calculated based on available memory.",
        "example": "--max-total-tokens 65536",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--page-size",
        "short": None,
        "category": "Memory & KV Cache",
        "type": "int",
        "default": "1",
        "description": "Number of tokens per KV cache page. Larger pages reduce overhead but waste memory.",
        "example": "--page-size 16",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--kv-cache-dtype",
        "short": None,
        "category": "Memory & KV Cache",
        "type": "choice",
        "default": "auto",
        "choices": ["auto", "fp8_e5m2", "fp8_e4m3", "bf16", "bfloat16", "fp4_e2m1"],
        "description": "Data type for KV cache. FP8 reduces memory by ~50% vs FP16 with minimal quality loss.",
        "example": "--kv-cache-dtype fp8_e4m3",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--disable-radix-cache",
        "short": None,
        "category": "Memory & KV Cache",
        "type": "flag",
        "default": "False",
        "description": "Disable RadixAttention prefix caching (may reduce throughput for shared-prefix workloads)",
        "example": "--disable-radix-cache",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--enable-hierarchical-cache",
        "short": None,
        "category": "Memory & KV Cache",
        "type": "flag",
        "default": "False",
        "description": "Enable hierarchical KV cache (HiCache) for CPU + GPU tiered caching",
        "example": "--enable-hierarchical-cache",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--cpu-offload-gb",
        "short": None,
        "category": "Memory & KV Cache",
        "type": "int",
        "default": "0",
        "description": "Offload KV cache to CPU when GPU memory is full (experimental)",
        "example": "--cpu-offload-gb 16",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--radix-eviction-policy",
        "short": None,
        "category": "Memory & KV Cache",
        "type": "choice",
        "default": "lru",
        "choices": ["lru", "lfu", "slru", "priority"],
        "description": "Eviction policy for RadixAttention prefix cache. LRU evicts least recently used prefixes.",
        "example": "--radix-eviction-policy lfu",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },

    # ===== Scheduling =====
    {
        "name": "--max-running-requests",
        "short": None,
        "category": "Scheduling",
        "type": "int",
        "default": "Auto",
        "description": "Maximum number of requests that can run concurrently",
        "example": "--max-running-requests 64",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--max-queued-requests",
        "short": None,
        "category": "Scheduling",
        "type": "int",
        "default": "Auto",
        "description": "Maximum number of requests that can be queued",
        "example": "--max-queued-requests 128",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--schedule-policy",
        "short": None,
        "category": "Scheduling",
        "type": "choice",
        "default": "fcfs",
        "choices": ["lpm", "random", "fcfs", "dfs-weight", "lof", "priority", "routing-key"],
        "description": "Scheduling policy for request batching. FCFS = First Come First Served. LPM = Longest Prefix Match.",
        "example": "--schedule-policy lpm",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--chunked-prefill-size",
        "short": None,
        "category": "Scheduling",
        "type": "int",
        "default": "Auto (-1 = disabled)",
        "description": "Number of tokens per chunk during prefill. Chunking prevents OOM on long prompts.",
        "example": "--chunked-prefill-size 4096",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--max-prefill-tokens",
        "short": None,
        "category": "Scheduling",
        "type": "int",
        "default": "16384",
        "description": "Maximum tokens in a single prefill batch",
        "example": "--max-prefill-tokens 8192",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--enable-priority-scheduling",
        "short": None,
        "category": "Scheduling",
        "type": "flag",
        "default": "False",
        "description": "Enable priority-based request scheduling. Requires clients to set priority header.",
        "example": "--enable-priority-scheduling",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--schedule-conservativeness",
        "short": None,
        "category": "Scheduling",
        "type": "float",
        "default": "0.0",
        "description": "Higher values make scheduling more conservative (fewer preemptions). Range: 0.0 to 1.0.",
        "example": "--schedule-conservativeness 0.5",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },

    # ===== Quantization & Data Types =====
    {
        "name": "--quantization",
        "short": None,
        "category": "Quantization & Data Types",
        "type": "choice",
        "default": "None",
        "choices": ["awq", "fp8", "mxfp8", "gptq", "marlin", "gptq_marlin", "awq_marlin", "bitsandbytes", "gguf", "modelopt", "w8a8_int8", "w8a8_fp8", "moe_wna16", "mxfp4", "auto-round", "compressed-tensors"],
        "description": "Quantization method for the model. Reduces memory usage and can improve throughput.",
        "example": "--quantization awq",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--enable-fp32-lm-head",
        "short": None,
        "category": "Quantization & Data Types",
        "type": "flag",
        "default": "False",
        "description": "Keep the LM head (final logits layer) in FP32 for better accuracy",
        "example": "--enable-fp32-lm-head",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },

    # ===== Multimodal =====
    {
        "name": "--enable-multimodal",
        "short": None,
        "category": "Multimodal",
        "type": "flag",
        "default": "False",
        "description": "Enable multimodal support (vision, audio). Required for VLMs and audio models.",
        "example": "--enable-multimodal",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--keep-mm-feature-on-device",
        "short": None,
        "category": "Multimodal",
        "type": "flag",
        "default": "False",
        "description": "Keep multimodal features (image embeddings) on GPU. Lower latency but more VRAM usage.",
        "example": "--keep-mm-feature-on-device",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--mm-attention-backend",
        "short": None,
        "category": "Multimodal",
        "type": "choice",
        "default": "Auto",
        "choices": ["sdpa", "fa3", "fa4", "triton_attn", "ascend_attn"],
        "description": "Attention backend for multimodal processing",
        "example": "--mm-attention-backend fa3",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--limit-mm-data-per-request",
        "short": None,
        "category": "Multimodal",
        "type": "int",
        "default": "None",
        "description": "Maximum number of multimodal items (images/video frames) per request",
        "example": "--limit-mm-data-per-request 5",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--disable-fast-image-processor",
        "short": None,
        "category": "Multimodal",
        "type": "flag",
        "default": "False",
        "description": "Disable fast image processor (fall back to HF image processor)",
        "example": "--disable-fast-image-processor",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },

    # ===== Speculative Decoding =====
    {
        "name": "--speculative-algorithm",
        "short": None,
        "category": "Speculative Decoding",
        "type": "choice",
        "default": "None",
        "choices": ["eagle", "medusa", "ngram", "dflash"],
        "description": "Speculative decoding algorithm. Uses a smaller draft model to predict tokens, verified by target model.",
        "example": "--speculative-algorithm eagle",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--speculative-draft-model-path",
        "short": None,
        "category": "Speculative Decoding",
        "type": "string",
        "default": "None",
        "description": "Path to the draft model used for speculative decoding (usually smaller than target model)",
        "example": "--speculative-draft-model-path meta-llama/Llama-3.2-1B-Instruct",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--speculative-num-steps",
        "short": None,
        "category": "Speculative Decoding",
        "type": "int",
        "default": "5",
        "description": "Number of speculative steps (tokens generated by draft model per verification pass)",
        "example": "--speculative-num-steps 3",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--speculative-eagle-topk",
        "short": None,
        "category": "Speculative Decoding",
        "type": "int",
        "default": "5",
        "description": "Top-K for EAGLE speculative decoding draft model",
        "example": "--speculative-eagle-topk 8",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--speculative-num-draft-tokens",
        "short": None,
        "category": "Speculative Decoding",
        "type": "int",
        "default": "Auto",
        "description": "Number of tokens the draft model generates per step",
        "example": "--speculative-num-draft-tokens 10",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--speculative-ngram-match-type",
        "short": None,
        "category": "Speculative Decoding",
        "type": "choice",
        "default": "BFS",
        "choices": ["BFS", "PROB"],
        "description": "Match type for n-gram speculative decoding",
        "example": "--speculative-ngram-match-type PROB",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },

    # ===== MoE & Expert Parallel =====
    {
        "name": "--moe-runner-backend",
        "short": None,
        "category": "MoE & Expert Parallel",
        "type": "choice",
        "default": "auto",
        "choices": ["auto", "deep_gemm", "triton", "cutlass", "flashinfer_trtllm", "aiter", "marlin"],
        "description": "Backend for Mixture-of-Experts (MoE) computation",
        "example": "--moe-runner-backend deep_gemm",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--moe-a2a-backend",
        "short": None,
        "category": "MoE & Expert Parallel",
        "type": "choice",
        "default": "none",
        "choices": ["none", "deepep", "mooncake", "nixl", "flashinfer"],
        "description": "All-to-all communication backend for expert parallelism",
        "example": "--moe-a2a-backend deepep",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--enable-eplb",
        "short": None,
        "category": "MoE & Expert Parallel",
        "type": "flag",
        "default": "False",
        "description": "Enable Expert Placement Load Balancing for MoE models",
        "example": "--enable-eplb",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },

    # ===== Monitoring & Logging =====
    {
        "name": "--enable-metrics",
        "short": None,
        "category": "Monitoring & Logging",
        "type": "flag",
        "default": "False",
        "description": "Enable Prometheus metrics endpoint at /metrics. Required for monitoring dashboard.",
        "example": "--enable-metrics",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--enable-mfu-metrics",
        "short": None,
        "category": "Monitoring & Logging",
        "type": "flag",
        "default": "False",
        "description": "Enable Model FLOPs Utilization (MFU) metrics",
        "example": "--enable-mfu-metrics",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--log-requests",
        "short": None,
        "category": "Monitoring & Logging",
        "type": "flag",
        "default": "False",
        "description": "Log all HTTP requests received by the server",
        "example": "--log-requests",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--log-level",
        "short": None,
        "category": "Monitoring & Logging",
        "type": "choice",
        "default": "info",
        "choices": ["debug", "info", "warning", "error", "critical"],
        "description": "Logging level for the server",
        "example": "--log-level debug",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--show-time-cost",
        "short": None,
        "category": "Monitoring & Logging",
        "type": "flag",
        "default": "False",
        "description": "Show time cost breakdown per request in logs",
        "example": "--show-time-cost",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },

    # ===== LoRA Adapters =====
    {
        "name": "--enable-lora",
        "short": None,
        "category": "LoRA Adapters",
        "type": "flag",
        "default": "False",
        "description": "Enable LoRA adapter serving. Allows loading multiple LoRA adapters simultaneously.",
        "example": "--enable-lora",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--max-lora-rank",
        "short": None,
        "category": "LoRA Adapters",
        "type": "int",
        "default": "64",
        "description": "Maximum rank for LoRA adapters",
        "example": "--max-lora-rank 128",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--max-loras-per-batch",
        "short": None,
        "category": "LoRA Adapters",
        "type": "int",
        "default": "8",
        "description": "Maximum number of different LoRA adapters in a single batch",
        "example": "--max-loras-per-batch 16",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },

    # ===== Advanced =====
    {
        "name": "--device",
        "short": None,
        "category": "Advanced",
        "type": "string",
        "default": "cuda",
        "description": "Device to run the model on (cuda, cpu, ascend)",
        "example": "--device cpu",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--disable-cuda-graph",
        "short": None,
        "category": "Advanced",
        "type": "flag",
        "default": "False",
        "description": "Disable CUDA graph optimization. May help with compatibility but reduces performance.",
        "example": "--disable-cuda-graph",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--enable-torch-compile",
        "short": None,
        "category": "Advanced",
        "type": "flag",
        "default": "False",
        "description": "Enable torch.compile for model optimization",
        "example": "--enable-torch-compile",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--attention-backend",
        "short": None,
        "category": "Advanced",
        "type": "choice",
        "default": "Auto",
        "choices": ["triton", "torch_native", "flex_attention", "fa3", "fa4", "flashinfer", "flashmla"],
        "description": "Attention computation backend. Different backends have different performance characteristics.",
        "example": "--attention-backend flashinfer",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--sampling-backend",
        "short": None,
        "category": "Advanced",
        "type": "choice",
        "default": "flashinfer",
        "choices": ["flashinfer", "pytorch"],
        "description": "Backend for token sampling operations",
        "example": "--sampling-backend pytorch",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--grammar-backend",
        "short": None,
        "category": "Advanced",
        "type": "choice",
        "default": "xgrammar",
        "choices": ["xgrammar", "outlines", "llguidance", "none"],
        "description": "Backend for structured output / grammar-constrained generation (JSON mode)",
        "example": "--grammar-backend outlines",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--random-seed",
        "short": None,
        "category": "Advanced",
        "type": "int",
        "default": "None",
        "description": "Random seed for deterministic generation",
        "example": "--random-seed 42",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--enable-cache-report",
        "short": None,
        "category": "Advanced",
        "type": "flag",
        "default": "False",
        "description": "Enable detailed cache hit/miss reporting",
        "example": "--enable-cache-report",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--watchdog-timeout",
        "short": None,
        "category": "Advanced",
        "type": "int",
        "default": "300",
        "description": "Timeout (seconds) for the watchdog thread that monitors server health",
        "example": "--watchdog-timeout 600",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--download-dir",
        "short": None,
        "category": "Advanced",
        "type": "string",
        "default": "~/.cache/huggingface",
        "description": "Directory to download HuggingFace models to",
        "example": "--download-dir /data/models",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--base-gpu-id",
        "short": None,
        "category": "Advanced",
        "type": "int",
        "default": "0",
        "description": "First GPU ID to use. Useful when you have multiple GPUs and want to skip some.",
        "example": "--base-gpu-id 1",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--enable-metrics-for-all-schedulers",
        "short": None,
        "category": "Advanced",
        "type": "flag",
        "default": "False",
        "description": "Enable metrics collection for all scheduler types",
        "example": "--enable-metrics-for-all-schedulers",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--allow-auto-truncate",
        "short": None,
        "category": "Advanced",
        "type": "flag",
        "default": "False",
        "description": "Automatically truncate prompts that exceed context length",
        "example": "--allow-auto-truncate",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--reasoning-parser",
        "short": None,
        "category": "Advanced",
        "type": "choice",
        "default": "auto",
        "choices": ["auto", "deepseek-r1", "deepseek-v3", "qwen3", "gemma4", "kimi", "mistral"],
        "description": "Parser for reasoning model outputs (extracts  reasoning content)",
        "example": "--reasoning-parser deepseek-r1",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--tool-call-parser",
        "short": None,
        "category": "Advanced",
        "type": "choice",
        "default": "auto",
        "choices": ["auto", "deepseekv3", "llama3", "qwen", "mistral", "gemma4"],
        "description": "Parser for tool/function call outputs",
        "example": "--tool-call-parser llama3",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
    {
        "name": "--enable-custom-logit-processor",
        "short": None,
        "category": "Advanced",
        "type": "flag",
        "default": "False",
        "description": "Enable custom logit processors (for advanced sampling control)",
        "example": "--enable-custom-logit-processor",
        "required": False,
        "supported_backends": ["sglang", "vllm", "llamacpp", "ollama"],
    },
]

# Build search index
ARGS_INDEX = {}
for arg in ARGS_REGISTRY:
    for key in (arg["name"], arg.get("short")):
        if key:
            ARGS_INDEX[key] = arg
    ARGS_INDEX[arg["name"].lstrip("-").replace("-", "_")] = arg


PRESETS = {
    "Low Latency": {
        "description": "Optimized for fast response times. Reduces batching for lower TTFT.",
        "args": {
            "chunked_prefill_size": 4096,
            "max_running_requests": 32,
            "schedule_policy": "lpm",
            "disable_radix_cache": False,
        },
    },
    "High Throughput": {
        "description": "Maximizes tokens/second for batch workloads.",
        "args": {
            "max_running_requests": 128,
            "schedule_policy": "fcfs",
            "enable_radix_cache": True,
        },
    },
    "Multimodal": {
        "description": "Configuration for vision-language and audio models.",
        "args": {
            "enable_multimodal": True,
            "keep_mm_feature_on_device": True,
        },
    },
    "GGUF": {
        "description": "For loading GGUF format models (from llama.cpp).",
        "args": {
            "load_format": "gguf",
        },
    },
    "Embeddings": {
        "description": "For embedding/retrieval models.",
        "args": {
            "is_embedding": True,
        },
    },
    "Speculative Decode": {
        "description": "Enable speculative decoding with a draft model for faster generation.",
        "args": {
            "speculative_algorithm": "eagle",
            "speculative_num_steps": 3,
            "speculative_eagle_topk": 5,
        },
    },
    "FP8 Quantization": {
        "description": "Use FP8 quantization for reduced memory and faster inference.",
        "args": {
            "quantization": "fp8",
        },
    },
    "Multi-GPU": {
        "description": "Tensor parallelism across 2 GPUs.",
        "args": {
            "tensor_parallel_size": 2,
        },
    },
    "CPU Offload": {
        "description": "Offload KV cache to CPU when GPU memory is limited.",
        "args": {
            "cpu_offload_gb": 16,
            "mem_fraction_static": 0.7,
        },
    },
}
